---
- name: "update yum packages."
  become: true
  yum:
    update_cache: true

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present